import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../componets/header/Header'
import { useAuth } from '../hooks/auth'
import { useProduct } from '../hooks/product'
import styles from '../styles/Home.module.css' 

const Home: NextPage = () => {
  const {data,error} = useAuth()
  const { data:products, error:errorProduct,remove} = useProduct()
  if(error || errorProduct) return <div>Failed to loading</div>
  if(!data || !products) return <div>Loading...</div>
  console.log('1');
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
          crossOrigin="anonymous"
        />
      </Head>
      <main >
        {data.map((item:any)=>(
          <p key={item.id}>{item.email}</p>
        ))}
       {products.map((item:any)=>(
        <div key={item.id}>{item.name} <button onClick={()=>remove(item.id)}>Remove</button></div>
       ))}
      </main>
    </div>
  )
}

export default Home
